---
- name: 'Import validator'
  tags:
    - always
  ansible.builtin.import_tasks: 'validator/main.yml'

- name: 'Import knot'
  become: true
  become_user: 'root'
  ansible.builtin.import_tasks: 'knot/main.yml'

- name: 'Import logrotate'
  become: true
  become_user: 'root'
  ansible.builtin.import_tasks: 'logrotate/main.yml'

- name: 'Import knot_rest tasks'
  ansible.builtin.import_tasks: 'knot_rest/main.yml'
