---
- name: 'Logrotate | Deploy configuration'
  tags:
    - install
    - knot_install
    - configure
    - knot_configure
  ansible.builtin.template:
    dest: '/etc/logrotate.d/knot'
    src: 'logrotate/knot.j2'
    owner: 'root'
    group: 'root'
    mode: '0644'
