---
- name: 'Knot | Install | INCLUDE => Import debian based tasks'
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: 'knot/install/debian/main.yml'

- name: 'Knot | Install | INCLUDE => Import RHEL based tasks'
  when: ansible_os_family == 'RedHat'
  ansible.builtin.include_tasks: 'knot/install/rhel/main.yml'

- name: 'Knot | Install | Install KNOT server package'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: present
    name: knot
