---
- name: 'Import install'
  tags:
    - install
    - knot_install
  ansible.builtin.import_tasks: 'knot/install/main.yml'


- name: 'Import configure'
  tags:
    - install
    - knot_install
    - configure
    - knot_configure
  ansible.builtin.import_tasks: 'knot/configure/main.yml'

