---
- name: 'Import install'
  ansible.builtin.import_tasks: 'knot/install/main.yml'
  tags:
    - install

- name: 'Import configure'
  ansible.builtin.import_tasks: 'knot/configure/main.yml'
  tags:
    - configure
